### ISSUE TITLE
Way too expensive

### ISSUE THREAD

**Issue by filfat** [liamcottle/Casper-API-Developers-PHP#1]
This is an awesome solution to get SwiftSnapper back on track, however 2000$ a month for an open source project is way too much (unlimited requests would be required as we're building a backend but rather an app). Is there a community subscription in the works?

**Comment by mentos1386** [comment]
+1

**Comment by teknogeek** [comment]
find someone else to provide a snapchat API then :')

**Comment by teknogeek** [comment]
maybe email snapchat and ask them? i'm sure they're lads

**Comment by teknogeek** [comment]
oh yeah. also why would this cater to _your_ project specifically? not sure i see why Liam should have to change his prices for you...

**Comment by filfat** [comment]
@teknogeek I think you missed the point.
While this is awesome for closed source income-generating projects it's not suited for open source projects that dosen't generate an large monthly income. Since this is the only option, asking for a price reduction or community subscription seems fair.

I never said that this is only to target our project specifically but rather that it's an "awesome solution"; maybe you missed that in the hurry to sheit on someone?

**Comment by Ahuge** [comment]
+1

Perhaps there is some way that an open source project to partner up with Liam, branding maybe?

**Comment by teknogeek** [comment]
well taking a look at your gitter chat, I don't think I missed much at all. You were using the Casper private API without permission and now you are upset and annoyed that you can't get your way anymore. also I rely do love shitting on people, thanks for noticing :simple_smile:
