### ISSUE TITLE
Post Story 

### ISSUE THREAD

**Issue by kripsbro** [liamcottle/Casper-API-Developers-PHP#2]
$snapchat->sendMedia($target_file, $_POST['time'], array(), true);
[POST] [https://app.snapchat.com/bq/post_story] HTTP/1.1 404 Not Found";

**Comment by liamcottle** [comment]
Hiya, please post these issues on the Snapchat-SDK-PHP repo.
However, this will happen if the file you uploaded via `uploadMedia` has expired, or did not upload.
